import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LoginLayout from "@/components/layouts/LoginLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full bg-gray-50">
      <body className={`${inter.className} h-full`}>
        <LoginLayout>{children}</LoginLayout>
      </body>
    </html>
  );
}
